import { JOIN_TEAM_URL, KIND_DIRECTORY_FORM_URL, NEW } from './index';
import {
  ABOUT_US_URL,
  CONTACTS_URL,
  JOURNAL_URL,
  KIND_DIRECTORY_URL,
  KIND_STORIES_OPEN_URL,
  KIND_STORIES_URL,
  MAIN_PAGE_URL,
  NEWS,
  NEWS_OPEN,
  SUPPORT_URL,
  TELL_STORY_URL,
  PARTNERS_URL,
  FEEDBACK_URL,
  FEEDBACK_ID_URL,
  OUR_TEAM_URL,
  SERVER_ERROR_URL,
  BECOME_PARTNER_URL,
} from '@/shared/constants/navigation/index.ts';

export const page = {
  mainPage: MAIN_PAGE_URL,
  kindStories: KIND_STORIES_URL,
  kindStoriesOpen: KIND_STORIES_OPEN_URL,
  kindDirectory: KIND_DIRECTORY_URL,
  kindDirectoryForm: KIND_DIRECTORY_FORM_URL,
  journal: JOURNAL_URL,
  aboutUs: ABOUT_US_URL,
  news: NEWS,
  new: NEW,
  newsOpen: NEWS_OPEN,
  contacts: CONTACTS_URL,
  support: SUPPORT_URL,
  tellStory: TELL_STORY_URL,
  joinTeam: JOIN_TEAM_URL,
  partners: PARTNERS_URL,
  reviews: FEEDBACK_URL,
  review: FEEDBACK_ID_URL,
  ourTeam: OUR_TEAM_URL,
  serverError: SERVER_ERROR_URL,
  becomePartner: BECOME_PARTNER_URL,
};
